import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar } from '@/components/sections/navbar'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shristi Gupta Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(" grid gap-24", inter.className)}>
          <Navbar/>
          {children}
      </body>
    </html>
  )
}
